version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"    
            
      columns:
          - name: orders_id
            description: test
            tests :
            - not_null 

          - name: products_id
            description: test
            tests:
            - not_null

          - name: qty

          - name: turnover
            description: test
            tests:
            - not_null

          - name: purchase_cost
            description: test
            tests:
            - not_null

          - name: margin
            description: test


